samuelcolvin/nosht

js/src/cats/Dashboard.js, js/src/events/Book.js, js/src/events/BookingLogin.js, js/src/events/BookingStripe.js, js/src/events/BookingTickets.js, js/src/events/Create.js, js/src/forms/Form.js, js/src/users/Account.js, js/src/users/Dashboard.js, py/shared/sql/models.sql, py/tests/test_cats.py, py/tests/test_events.py, py/tests/test_export.py, py/tests/test_users.py, py/web/views/categories.py, py/web/views/events.py, py/web/views/export.py, py/web/views/users.py
`terms_and_conditions_message`, `allow_marketing_message` and `booking_trust_message`
fix #7, fix #19
=> extra fields

py/shared/emails/defaults.py, py/shared/emails/main.py, py/shared/emails/plumbing.py, py/shared/emails/styles.scss, py/shared/sql/logic.sql, py/shared/sql/models.sql, py/tests/test_email_defs.py, py/tests/test_emails.py, py/tests/test_events.py, py/tests/test_users.py, py/web/middleware.py, py/web/utils.py, py/web/views/events.py, py/web/views/export.py, py/web/views/users.py
=> improving emails

js/package.json, js/src/App.js, js/src/cats/Main.js, js/src/events/Dashboard.js, js/src/events/Main.js, js/src/events/TicketTypes.js, js/src/general/Dashboard.js, js/src/general/Navbar.js, js/src/styles/main.scss, js/yarn.lock, py/tests/test_cats.py, py/tests/test_users.py, py/web/bread/__init__.py, py/web/bread/main.py, py/web/middleware.py, py/web/utils.py, py/web/views/events.py, py/web/views/users.py
=> pagination and host on event

py/tests/dummy_server.py, py/tests/test_stripe.py, py/web/bread/view.py, py/web/stripe.py
=> shield stripe

js/src/cats/Dashboard.js, js/src/company/Dashboard.js, js/src/donations/Dashboard.js, js/src/emails/Dashboard.js, js/src/events/Dashboard.js, js/src/general/Dashboard.js, js/src/users/Account.js, js/src/users/Dashboard.js, py/tests/test_events.py, py/tests/test_utils.py, py/web/utils.py, py/web/views/events.py
=> editing past events

.gitignore, js/public/index.html, js/src/events/Cards.js, js/src/general/Navbar.js, js/src/styles/_theme.scss, js/src/styles/_variables.scss
=> theme changes

js/src/App.js, js/src/company/Dashboard.js, js/src/company/FooterLinks.js, js/src/general/Footer.js, js/src/styles/_theme.scss, py/shared/db.py, py/shared/sql/models.sql, py/tests/test_anon.py, py/tests/test_company_edit.py, py/tests/test_db.py, py/web/main.py, py/web/views/__init__.py, py/web/views/company.py
=> implement footer links

js/src/forms/Form.js, js/src/forms/Input.js, py/web/views/events.py
=> event creation and ordering

js/src/events/Book.js, js/src/events/BookingLogin.js, js/src/events/BookingTickets.js
=> guest fixes

py/shared/donorfy.py, py/tests/dummy_server.py, py/tests/test_donorfy.py
=> Donorfy campaigns

py/shared/donorfy.py, py/tests/dummy_server.py, py/tests/test_donorfy.py
=> add GiftAidDeclarations to constituent

py/shared/donorfy.py
=> remove 'ConnectedConstituentID'

py/shared/donorfy.py
=> remove ConnectedConstituentId the sequel 

js/src/events/Cards.js, js/src/events/Dashboard.js, js/src/events/Main.js, js/src/general/Dashboard.js, js/src/styles/_theme.scss, py/shared/db.py, py/shared/images.py, py/shared/sql/models.sql, py/tests/test_cats.py, py/tests/test_events.py, py/web/main.py, py/web/middleware.py, py/web/views/categories.py, py/web/views/events.py
=> add secondary image

js/src/events/Dashboard.js, js/src/general/Dashboard.js, py/tests/test_events.py, py/tests/test_middleware.py, py/web/main.py, py/web/views/events.py
=> Remove secondary image

js/src/events/Create.js, js/src/events/Dashboard.js, js/src/events/Main.js, js/src/forms/Input.js, py/requirements.txt, py/shared/db.py, py/shared/sql/models.sql, py/tests/test_booking.py, py/tests/test_events.py, py/web/utils.py, py/web/views/booking.py, py/web/views/events.py
=> External Ticketing

py/tests/test_events.py, py/web/views/events.py
=> remove duplicate tickets

py/shared/donorfy.py, py/shared/stripe_base.py, py/tests/conftest.py, py/tests/dummy_server.py, py/tests/test_donate.py, py/tests/test_donorfy.py, py/tests/test_stripe.py, py/web/stripe.py, py/web/views/stripe.py
=> Card processing fees

py/web/views/booking.py
=> fix ticket info order on booking

py/shared/donorfy.py, py/tests/test_donorfy.py
=> fix perferences in donorfy

py/tests/conftest.py, py/tests/test_stripe.py, py/web/views/stripe.py
ignore stripe webhooks for charges not created in nosht
=> stripe webhook handling

js/src/events/Stripe.js, py/tests/dummy_server.py, py/tests/test_stripe.py, py/web/stripe.py, py/web/views/stripe.py
=> expire payment methods after 1 hour

py/tests/test_booking.py, py/web/views/booking.py
=> inactive ticket types

js/src/events/Cards.js, py/tests/test_anon.py, py/tests/test_booking.py, py/tests/test_cats.py, py/tests/test_db.py, py/web/views/__init__.py, py/web/views/categories.py
=> add sold out badge

js/src/cats/Dashboard.js, js/src/company/Dashboard.js, js/src/donations/Dashboard.js, js/src/emails/Dashboard.js, js/src/events/Dashboard.js, js/src/forms/Input.js, js/src/general/Dashboard.js, js/src/general/Modal.js, js/src/users/Account.js, js/src/users/Dashboard.js, py/requirements.txt, py/tests/test_events.py, py/web/main.py, py/web/views/events.py, py/web/views/static.py
=> cloning events

js/src/events/Dashboard.js
=> fix admin event dashboard
